algoritmo "Contador"
// Função : Estrutura de Repetição
// Autor : Juliana Malveira
// Data : 22/11/2025

var
      contador, N, s: inteiro
inicio
// Seção de Comandos 
contador <-1
S <- 0

Enquanto (contador <= 5) faca
 escreval ("Digite o ", contador,"o. valor:" )
 Leia (N)
 S <- S + N
 Contador <- Contador + 1

FimEnquanto
Escreval ("A soma de todos os valores é:", s)

fimalgoritmo
