algoritmo "Contador"
// Função : Estrutura de Repetição
// Autor : Juliana Malveira
// Data : 22/11/2025

var
      valor,salto, contador: inteiro
inicio
// Seção de Comandos 
contador <-0
Escreval ("Quer contar até quanto?")
leia (valor)

Escreval ("Qual valor do salto?")
leia (salto)

Enquanto contador <= valor faca
 escreval (contador)
   contador <- contador + salto

FimEnquanto

fimalgoritmo
