Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 04/08/2023
Var
// Seção de Declarações das variáveis 
A,B,C,D: INTEIRO


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
A <- 1
B <- 4
C <- 2
D <- 1

ESCREVA (D<C)

Fimalgoritmo