algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
var
A, B: real

//Faça um programa que leia as duas notas de um aluno em uma matéria e mostre
//na tela a sua média na disciplina.
//Ex:
//Nota 1: 4.5
//Nota 2: 8.5
//A média entre 4.5 e 8.5 é igual a 6.5

inicio
Escreva ("Nota 1: ")
Leia (A)
Escreva ("Nota 2: ")
Leia (B)
Escreva ("A média entre ", A, " e ", B, " é igual a ", (A+B)/2, ".")


fimalgoritmo
