algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
// Função :
// Autor :
// Data : 04/02/2025
// Seção de Declarações 
var

   reais,cotacao,dolar: Real
inicio
// Seção de Comandos 
Escreva ("Quanto você tem em reais? R$")
Leia (reais)
Escreva ("Qual a cotação do dólar hoje? ")
Leia (cotacao)

dolar <- reais / cotacao

Escreva ("O valor em dólar será US$", dolar)

fimalgoritmo
