algoritmo "IDADE ATUAL"
// Função :
// Autor :
// Data : 03/02/2025
// Seção de Declarações 
var
   ano_atual, ano_nasc, idade: inteiro
   
inicio
// Seção de Comandos 
        Escreva ("Qual o ano atual? ")
        Leia (ano_atual)
        Escreva ("Qual o ano do nascimento? ")
        Leia (ano_nasc)
        idade <- ano_atual - ano_nasc
        Escreva ("Sua idade é: ", idade)

fimalgoritmo
